import motor.motor_asyncio
import asyncio
import os
from datetime import datetime, timedelta
from dotenv import load_dotenv
import uuid

# Load environment variables
load_dotenv()

# MongoDB connection
MONGO_URL = os.getenv("MONGO_URL", "mongodb://localhost:27017/booktime")
client = motor.motor_asyncio.AsyncIOMotorClient(MONGO_URL)
database = client.booktime
books_collection = database.books

# Sample data for books
books_data = [
    # Harry Potter saga (3 books)
    {
        "_id": str(uuid.uuid4()),
        "title": "Harry Potter à l'école des sorciers",
        "author": "J.K. Rowling",
        "category": "roman",
        "description": "Le premier tome de la saga Harry Potter",
        "cover_url": "https://example.com/harry-potter-1.jpg",
        "total_pages": 309,
        "isbn": "978-2-07-054102-9",
        "saga": "Harry Potter",
        "volume_number": 1,
        "publication_year": 1997,
        "publisher": "Gallimard",
        "genre": ["fantasy", "young adult"],
        "original_language": "anglais",
        "available_translations": ["français", "espagnol", "allemand"],
        "reading_language": "français",
        "status": "completed",
        "current_page": 309,
        "rating": 5,
        "review": "Un classique incontournable",
        "date_added": datetime.utcnow() - timedelta(days=100),
        "date_started": datetime.utcnow() - timedelta(days=95),
        "date_completed": datetime.utcnow() - timedelta(days=90),
        "auto_added": False
    },
    {
        "_id": str(uuid.uuid4()),
        "title": "Harry Potter et la Chambre des Secrets",
        "author": "J.K. Rowling",
        "category": "roman",
        "description": "Le deuxième tome de la saga Harry Potter",
        "cover_url": "https://example.com/harry-potter-2.jpg",
        "total_pages": 368,
        "isbn": "978-2-07-052455-8",
        "saga": "Harry Potter",
        "volume_number": 2,
        "publication_year": 1998,
        "publisher": "Gallimard",
        "genre": ["fantasy", "young adult"],
        "original_language": "anglais",
        "available_translations": ["français", "espagnol", "allemand"],
        "reading_language": "français",
        "status": "completed",
        "current_page": 368,
        "rating": 4,
        "review": "Encore meilleur que le premier",
        "date_added": datetime.utcnow() - timedelta(days=85),
        "date_started": datetime.utcnow() - timedelta(days=80),
        "date_completed": datetime.utcnow() - timedelta(days=75),
        "auto_added": False
    },
    {
        "_id": str(uuid.uuid4()),
        "title": "Harry Potter et le Prisonnier d'Azkaban",
        "author": "J.K. Rowling",
        "category": "roman",
        "description": "Le troisième tome de la saga Harry Potter",
        "cover_url": "https://example.com/harry-potter-3.jpg",
        "total_pages": 448,
        "isbn": "978-2-07-052457-2",
        "saga": "Harry Potter",
        "volume_number": 3,
        "publication_year": 1999,
        "publisher": "Gallimard",
        "genre": ["fantasy", "young adult"],
        "original_language": "anglais",
        "available_translations": ["français", "espagnol", "allemand"],
        "reading_language": "français",
        "status": "completed",
        "current_page": 448,
        "rating": 5,
        "review": "Mon préféré de la série",
        "date_added": datetime.utcnow() - timedelta(days=70),
        "date_started": datetime.utcnow() - timedelta(days=65),
        "date_completed": datetime.utcnow() - timedelta(days=60),
        "auto_added": False
    },
    
    # One Piece saga (3 books)
    {
        "_id": str(uuid.uuid4()),
        "title": "One Piece - Tome 1",
        "author": "Eiichiro Oda",
        "category": "manga",
        "description": "Le début de l'aventure de Luffy",
        "cover_url": "https://example.com/one-piece-1.jpg",
        "total_pages": 208,
        "isbn": "978-2-7234-4123-5",
        "saga": "One Piece",
        "volume_number": 1,
        "publication_year": 1997,
        "publisher": "Glénat",
        "genre": ["aventure", "action", "fantasy"],
        "original_language": "japonais",
        "available_translations": ["français", "anglais"],
        "reading_language": "français",
        "status": "completed",
        "current_page": 208,
        "rating": 5,
        "review": "Le début d'une grande aventure",
        "date_added": datetime.utcnow() - timedelta(days=200),
        "date_started": datetime.utcnow() - timedelta(days=195),
        "date_completed": datetime.utcnow() - timedelta(days=190),
        "auto_added": False
    },
    {
        "_id": str(uuid.uuid4()),
        "title": "One Piece - Tome 2",
        "author": "Eiichiro Oda",
        "category": "manga",
        "description": "La suite des aventures de Luffy",
        "cover_url": "https://example.com/one-piece-2.jpg",
        "total_pages": 208,
        "isbn": "978-2-7234-4124-2",
        "saga": "One Piece",
        "volume_number": 2,
        "publication_year": 1997,
        "publisher": "Glénat",
        "genre": ["aventure", "action", "fantasy"],
        "original_language": "japonais",
        "available_translations": ["français", "anglais"],
        "reading_language": "français",
        "status": "completed",
        "current_page": 208,
        "rating": 5,
        "review": "Toujours aussi bon",
        "date_added": datetime.utcnow() - timedelta(days=185),
        "date_started": datetime.utcnow() - timedelta(days=180),
        "date_completed": datetime.utcnow() - timedelta(days=175),
        "auto_added": False
    },
    {
        "_id": str(uuid.uuid4()),
        "title": "One Piece - Tome 3",
        "author": "Eiichiro Oda",
        "category": "manga",
        "description": "La suite des aventures de Luffy",
        "cover_url": "https://example.com/one-piece-3.jpg",
        "total_pages": 208,
        "isbn": "978-2-7234-4125-9",
        "saga": "One Piece",
        "volume_number": 3,
        "publication_year": 1998,
        "publisher": "Glénat",
        "genre": ["aventure", "action", "fantasy"],
        "original_language": "japonais",
        "available_translations": ["français", "anglais"],
        "reading_language": "français",
        "status": "completed",
        "current_page": 208,
        "rating": 5,
        "review": "L'aventure continue",
        "date_added": datetime.utcnow() - timedelta(days=170),
        "date_started": datetime.utcnow() - timedelta(days=165),
        "date_completed": datetime.utcnow() - timedelta(days=160),
        "auto_added": False
    },
    
    # Naruto saga (3 books)
    {
        "_id": str(uuid.uuid4()),
        "title": "Naruto - Tome 1",
        "author": "Masashi Kishimoto",
        "category": "manga",
        "description": "Le début de l'aventure de Naruto",
        "cover_url": "https://example.com/naruto-1.jpg",
        "total_pages": 192,
        "isbn": "978-2-87129-627-8",
        "saga": "Naruto",
        "volume_number": 1,
        "publication_year": 1999,
        "publisher": "Kana",
        "genre": ["action", "fantasy", "ninja"],
        "original_language": "japonais",
        "available_translations": ["français", "anglais"],
        "reading_language": "français",
        "status": "completed",
        "current_page": 192,
        "rating": 4,
        "review": "Un classique du manga",
        "date_added": datetime.utcnow() - timedelta(days=150),
        "date_started": datetime.utcnow() - timedelta(days=145),
        "date_completed": datetime.utcnow() - timedelta(days=140),
        "auto_added": False
    },
    {
        "_id": str(uuid.uuid4()),
        "title": "Naruto - Tome 2",
        "author": "Masashi Kishimoto",
        "category": "manga",
        "description": "La suite des aventures de Naruto",
        "cover_url": "https://example.com/naruto-2.jpg",
        "total_pages": 192,
        "isbn": "978-2-87129-628-5",
        "saga": "Naruto",
        "volume_number": 2,
        "publication_year": 2000,
        "publisher": "Kana",
        "genre": ["action", "fantasy", "ninja"],
        "original_language": "japonais",
        "available_translations": ["français", "anglais"],
        "reading_language": "français",
        "status": "completed",
        "current_page": 192,
        "rating": 4,
        "review": "L'histoire se développe bien",
        "date_added": datetime.utcnow() - timedelta(days=135),
        "date_started": datetime.utcnow() - timedelta(days=130),
        "date_completed": datetime.utcnow() - timedelta(days=125),
        "auto_added": False
    },
    {
        "_id": str(uuid.uuid4()),
        "title": "Naruto - Tome 3",
        "author": "Masashi Kishimoto",
        "category": "manga",
        "description": "La suite des aventures de Naruto",
        "cover_url": "https://example.com/naruto-3.jpg",
        "total_pages": 192,
        "isbn": "978-2-87129-629-2",
        "saga": "Naruto",
        "volume_number": 3,
        "publication_year": 2000,
        "publisher": "Kana",
        "genre": ["action", "fantasy", "ninja"],
        "original_language": "japonais",
        "available_translations": ["français", "anglais"],
        "reading_language": "français",
        "status": "reading",
        "current_page": 100,
        "rating": None,
        "review": None,
        "date_added": datetime.utcnow() - timedelta(days=120),
        "date_started": datetime.utcnow() - timedelta(days=115),
        "date_completed": None,
        "auto_added": False
    },
    
    # Tintin saga (2 books)
    {
        "_id": str(uuid.uuid4()),
        "title": "Tintin au Tibet",
        "author": "Hergé",
        "category": "bd",
        "description": "Les aventures de Tintin au Tibet",
        "cover_url": "https://example.com/tintin-tibet.jpg",
        "total_pages": 62,
        "isbn": "978-2-203-00113-2",
        "saga": "Tintin",
        "volume_number": 20,
        "publication_year": 1960,
        "publisher": "Casterman",
        "genre": ["aventure", "voyage"],
        "original_language": "français",
        "available_translations": ["anglais", "espagnol"],
        "reading_language": "français",
        "status": "completed",
        "current_page": 62,
        "rating": 5,
        "review": "Un des meilleurs Tintin",
        "date_added": datetime.utcnow() - timedelta(days=300),
        "date_started": datetime.utcnow() - timedelta(days=295),
        "date_completed": datetime.utcnow() - timedelta(days=290),
        "auto_added": False
    },
    {
        "_id": str(uuid.uuid4()),
        "title": "Le Lotus Bleu",
        "author": "Hergé",
        "category": "bd",
        "description": "Les aventures de Tintin en Chine",
        "cover_url": "https://example.com/tintin-lotus.jpg",
        "total_pages": 62,
        "isbn": "978-2-203-00104-0",
        "saga": "Tintin",
        "volume_number": 5,
        "publication_year": 1936,
        "publisher": "Casterman",
        "genre": ["aventure", "voyage"],
        "original_language": "français",
        "available_translations": ["anglais", "espagnol"],
        "reading_language": "français",
        "status": "completed",
        "current_page": 62,
        "rating": 5,
        "review": "Un classique",
        "date_added": datetime.utcnow() - timedelta(days=280),
        "date_started": datetime.utcnow() - timedelta(days=275),
        "date_completed": datetime.utcnow() - timedelta(days=270),
        "auto_added": False
    },
    
    # Astérix saga (2 books)
    {
        "_id": str(uuid.uuid4()),
        "title": "Astérix le Gaulois",
        "author": "René Goscinny",
        "category": "bd",
        "description": "Le premier album d'Astérix",
        "cover_url": "https://example.com/asterix-1.jpg",
        "total_pages": 48,
        "isbn": "978-2-01-210133-7",
        "saga": "Astérix",
        "volume_number": 1,
        "publication_year": 1961,
        "publisher": "Dargaud",
        "genre": ["humour", "histoire"],
        "original_language": "français",
        "available_translations": ["anglais", "allemand"],
        "reading_language": "français",
        "status": "completed",
        "current_page": 48,
        "rating": 4,
        "review": "Le début d'une grande série",
        "date_added": datetime.utcnow() - timedelta(days=250),
        "date_started": datetime.utcnow() - timedelta(days=245),
        "date_completed": datetime.utcnow() - timedelta(days=240),
        "auto_added": False
    },
    {
        "_id": str(uuid.uuid4()),
        "title": "Astérix et Cléopâtre",
        "author": "René Goscinny",
        "category": "bd",
        "description": "Les aventures d'Astérix en Égypte",
        "cover_url": "https://example.com/asterix-cleopatre.jpg",
        "total_pages": 48,
        "isbn": "978-2-01-210136-8",
        "saga": "Astérix",
        "volume_number": 6,
        "publication_year": 1965,
        "publisher": "Dargaud",
        "genre": ["humour", "histoire"],
        "original_language": "français",
        "available_translations": ["anglais", "allemand"],
        "reading_language": "français",
        "status": "reading",
        "current_page": 30,
        "rating": None,
        "review": None,
        "date_added": datetime.utcnow() - timedelta(days=230),
        "date_started": datetime.utcnow() - timedelta(days=225),
        "date_completed": None,
        "auto_added": False
    },
    
    # Standalone books
    {
        "_id": str(uuid.uuid4()),
        "title": "Le Petit Prince",
        "author": "Antoine de Saint-Exupéry",
        "category": "roman",
        "description": "Un conte philosophique sous forme d'un récit pour enfants",
        "cover_url": "https://example.com/petit-prince.jpg",
        "total_pages": 96,
        "isbn": "978-2-07-040850-4",
        "publication_year": 1943,
        "publisher": "Gallimard",
        "genre": ["conte", "philosophie"],
        "original_language": "français",
        "available_translations": ["anglais", "espagnol", "allemand"],
        "reading_language": "français",
        "status": "completed",
        "current_page": 96,
        "rating": 5,
        "review": "Un chef-d'œuvre intemporel",
        "date_added": datetime.utcnow() - timedelta(days=400),
        "date_started": datetime.utcnow() - timedelta(days=395),
        "date_completed": datetime.utcnow() - timedelta(days=390),
        "auto_added": False
    },
    {
        "_id": str(uuid.uuid4()),
        "title": "1984",
        "author": "George Orwell",
        "category": "roman",
        "description": "Un roman dystopique sur la surveillance de masse",
        "cover_url": "https://example.com/1984.jpg",
        "total_pages": 328,
        "isbn": "978-2-07-036822-8",
        "publication_year": 1949,
        "publisher": "Gallimard",
        "genre": ["science-fiction", "dystopie"],
        "original_language": "anglais",
        "available_translations": ["français", "espagnol"],
        "reading_language": "français",
        "status": "reading",
        "current_page": 200,
        "rating": None,
        "review": None,
        "date_added": datetime.utcnow() - timedelta(days=50),
        "date_started": datetime.utcnow() - timedelta(days=45),
        "date_completed": None,
        "auto_added": False
    },
    {
        "_id": str(uuid.uuid4()),
        "title": "L'Étranger",
        "author": "Albert Camus",
        "category": "roman",
        "description": "Un roman existentialiste",
        "cover_url": "https://example.com/etranger.jpg",
        "total_pages": 184,
        "isbn": "978-2-07-036002-4",
        "publication_year": 1942,
        "publisher": "Gallimard",
        "genre": ["philosophie", "existentialisme"],
        "original_language": "français",
        "available_translations": ["anglais", "allemand"],
        "reading_language": "français",
        "status": "to_read",
        "current_page": 0,
        "rating": None,
        "review": None,
        "date_added": datetime.utcnow() - timedelta(days=30),
        "date_started": None,
        "date_completed": None,
        "auto_added": False
    },
    
    # Auto-added books (5 books)
    {
        "_id": str(uuid.uuid4()),
        "title": "Harry Potter et la Coupe de Feu",
        "author": "J.K. Rowling",
        "category": "roman",
        "description": "Tome 4 de la saga Harry Potter",
        "saga": "Harry Potter",
        "volume_number": 4,
        "publication_year": 2000,
        "publisher": "Gallimard",
        "genre": ["fantasy", "young adult"],
        "original_language": "anglais",
        "available_translations": ["français", "espagnol", "allemand"],
        "reading_language": "français",
        "status": "to_read",
        "current_page": 0,
        "date_added": datetime.utcnow() - timedelta(days=20),
        "auto_added": True
    },
    {
        "_id": str(uuid.uuid4()),
        "title": "One Piece - Tome 4",
        "author": "Eiichiro Oda",
        "category": "manga",
        "description": "Tome 4 de la saga One Piece",
        "saga": "One Piece",
        "volume_number": 4,
        "publication_year": 1998,
        "publisher": "Glénat",
        "genre": ["aventure", "action", "fantasy"],
        "original_language": "japonais",
        "available_translations": ["français", "anglais"],
        "reading_language": "français",
        "status": "to_read",
        "current_page": 0,
        "date_added": datetime.utcnow() - timedelta(days=15),
        "auto_added": True
    },
    {
        "_id": str(uuid.uuid4()),
        "title": "One Piece - Tome 5",
        "author": "Eiichiro Oda",
        "category": "manga",
        "description": "Tome 5 de la saga One Piece",
        "saga": "One Piece",
        "volume_number": 5,
        "publication_year": 1999,
        "publisher": "Glénat",
        "genre": ["aventure", "action", "fantasy"],
        "original_language": "japonais",
        "available_translations": ["français", "anglais"],
        "reading_language": "français",
        "status": "to_read",
        "current_page": 0,
        "date_added": datetime.utcnow() - timedelta(days=10),
        "auto_added": True
    },
    {
        "_id": str(uuid.uuid4()),
        "title": "Naruto - Tome 4",
        "author": "Masashi Kishimoto",
        "category": "manga",
        "description": "Tome 4 de la saga Naruto",
        "saga": "Naruto",
        "volume_number": 4,
        "publication_year": 2001,
        "publisher": "Kana",
        "genre": ["action", "fantasy", "ninja"],
        "original_language": "japonais",
        "available_translations": ["français", "anglais"],
        "reading_language": "français",
        "status": "to_read",
        "current_page": 0,
        "date_added": datetime.utcnow() - timedelta(days=5),
        "auto_added": True
    },
    {
        "_id": str(uuid.uuid4()),
        "title": "Astérix chez les Bretons",
        "author": "René Goscinny",
        "category": "bd",
        "description": "Tome 8 de la saga Astérix",
        "saga": "Astérix",
        "volume_number": 8,
        "publication_year": 1966,
        "publisher": "Dargaud",
        "genre": ["humour", "histoire"],
        "original_language": "français",
        "available_translations": ["anglais", "allemand"],
        "reading_language": "français",
        "status": "to_read",
        "current_page": 0,
        "date_added": datetime.utcnow() - timedelta(days=2),
        "auto_added": True
    }
]

async def populate_database():
    # Clear existing data
    await books_collection.delete_many({})
    
    # Insert new data
    await books_collection.insert_many(books_data)
    
    # Verify the data was inserted
    count = await books_collection.count_documents({})
    print(f"Inserted {count} books into the database")
    
    # Count by category
    roman_count = await books_collection.count_documents({"category": "roman"})
    bd_count = await books_collection.count_documents({"category": "bd"})
    manga_count = await books_collection.count_documents({"category": "manga"})
    
    print(f"Categories: roman={roman_count}, bd={bd_count}, manga={manga_count}")
    
    # Count by status
    completed_count = await books_collection.count_documents({"status": "completed"})
    reading_count = await books_collection.count_documents({"status": "reading"})
    to_read_count = await books_collection.count_documents({"status": "to_read"})
    
    print(f"Status: completed={completed_count}, reading={reading_count}, to_read={to_read_count}")
    
    # Count sagas and authors
    sagas = await books_collection.distinct("saga")
    authors = await books_collection.distinct("author")
    auto_added = await books_collection.count_documents({"auto_added": True})
    
    print(f"Sagas: {len(sagas)}")
    print(f"Authors: {len(authors)}")
    print(f"Auto-added books: {auto_added}")

if __name__ == "__main__":
    asyncio.run(populate_database())