/**
 * 🚀 EXTENDED SERIES DATABASE - BOOKTIME
 * Base de données étendue des séries populaires
 * 
 * Dernière mise à jour: 2025-07-12 01:37:56
 * Nombre de séries: 58
 * 
 * Généré automatiquement par: update_series_detection.py
 * Source: Open Library + base manuelle
 */

// Export pour modules ES6
export const EXTENDED_SERIES_DATABASE = [
  {
    name: "'king Zéus",
    authors: ["Steve Albert"],
    category: "roman",
    volumes: 8,
    keywords: ["'king zéus", "'king zéus series", "'king zéus saga", "the 'king zéus", "steve"],
    variations: ["'king Zéus", "The 'king Zéus", "'king Zéus Series"],
    source: "open_library_mega_expansion",
  },
  {
    name: "Adventures of Huckleberry Finn",
    authors: ["Mark Twain"],
    category: "roman",
    volumes: 1,
    keywords: ["huckleberry", "finn", "adventures"],
    variations: ["Adventures of Huckleberry Finn", "a Adventures of Huckleberry Finn", "an Adventures of Huckleberry Finn", "un Adventures of Huckleberry Finn", "les Adventures of Huckleberry Finn", "A Adventures of Huckleberry Finn", "the Adventures of Huckleberry Finn", "Adventures  Huckleberry Finn", "la Adventures of Huckleberry Finn", "Le Adventures of Huckleberry Finn", "des Adventures of Huckleberry Finn", "adventures of huckleberry finn", "le Adventures of Huckleberry Finn", "La Adventures of Huckleberry Finn", "ADVENTURES OF HUCKLEBERRY FINN", "Des Adventures of Huckleberry Finn", "Les Adventures of Huckleberry Finn", "Adventures Of Huckleberry Finn", "Un Adventures of Huckleberry Finn", "Une Adventures of Huckleberry Finn", "The Adventures of Huckleberry Finn", "An Adventures of Huckleberry Finn", "une Adventures of Huckleberry Finn", "Adv of Huckleberry Finn"],
    first_published: 1876,
    status: "ongoing",
    languages: ["kor", "ara", "eng", "arm", "por", "alb", "jpn", "pol", "ind", "tel", "vie", "ang", "hin", "per", "ger", "rus", "rum", "ita", "dut", "spa", "fre", "chi", "fin"],
    translations: {"en": "Adventures of Huckleberry Finn", "fr": "Adventures of Huckleberry Finn"},
    source: "open_library_search",
  },
  {
    name: "Alice's",
    authors: ["Lewis Carroll"],
    category: "roman",
    volumes: 2,
    keywords: ["alice's", "alice's series", "alice's saga", "the alice's", "lewis"],
    variations: ["Alice's", "The Alice's", "Alice's Series"],
    subjects: ["adventure and adventurers, fiction", "JUVENILE FICTION", "adventure travel", "adventure and adventurers", "classics", "animals", "Alice (fictitious character : carroll), fiction", "adventure stories", "Fiction, fantasy, general", "British and irish fiction (fictional works by one author)"],
    source: "open_library_mega_expansion",
  },
  {
    name: "Alice's Adventures in Wonderland",
    authors: ["Lewis Carroll"],
    category: "roman",
    volumes: 1,
    keywords: ["alice", "wonderland", "adventures"],
    variations: ["The Alice's Adventures in Wonderland", "le Alice's Adventures in Wonderland", "Alice's Adventures in Wonderland", "les Alice's Adventures in Wonderland", "des Alice's Adventures in Wonderland", "Des Alice's Adventures in Wonderland", "Alice's Adventures in Wonderl&", "un Alice's Adventures in Wonderland", "ALICE'S ADVENTURES IN WONDERLAND", "la Alice's Adventures in Wonderland", "an Alice's Adventures in Wonderland", "La Alice's Adventures in Wonderland", "Une Alice's Adventures in Wonderland", "Le Alice's Adventures in Wonderland", "A Alice's Adventures in Wonderland", "Les Alice's Adventures in Wonderland", "a Alice's Adventures in Wonderland", "Alice's Adv in Wonderland", "une Alice's Adventures in Wonderland", "alice's adventures in wonderland", "Un Alice's Adventures in Wonderland", "Alice'S Adventures In Wonderland", "An Alice's Adventures in Wonderland", "the Alice's Adventures in Wonderland"],
    first_published: 1865,
    status: "ongoing",
    languages: ["swe", "guj", "kir", "kor", "bul", "ara", "cor", "gre", "sco", "cat", "und", "eng", "kaz", "por", "haw", "dan", "syr", "swa", "crp", "jpn", "pol", "ceb", "tel", "lat", "bel", "hrv", "fry", "lad", "ger", "alt", "rus", "yid", "heb", "ita", "dut", "tur", "spa", "orm", "bre", "hun", "gle", "slo", "srp", "fre", "wel", "ukr", "chi", "fin", "epo", "lav", "cze"],
    translations: {"en": "Alice's Adventures in Wonderland", "fr": "Alice's Adventures in Wonderland"},
    source: "open_library_search",
  },
  {
    name: "Alice's Adventures in Wonderland / Through the Looking Glass",
    authors: ["Lewis Carroll"],
    category: "roman",
    volumes: 1,
    keywords: ["alice", "through", "adventures", "wonderland"],
    variations: ["an Alice's Adventures in Wonderland / Through the Looking Glass", "des Alice's Adventures in Wonderland / Through the Looking Glass", "Un Alice's Adventures in Wonderland / Through the Looking Glass", "A Alice's Adventures in Wonderland / Through the Looking Glass", "alice's adventures in wonderland / through the looking glass", "Le Alice's Adventures in Wonderland / Through the Looking Glass", "Alice's Adventures in Wonderl& / Through the Looking Glass", "les Alice's Adventures in Wonderland / Through the Looking Glass", "une Alice's Adventures in Wonderland / Through the Looking Glass", "Alice'S Adventures In Wonderland / Through The Looking Glass", "a Alice's Adventures in Wonderland / Through the Looking Glass", "Les Alice's Adventures in Wonderland / Through the Looking Glass", "Des Alice's Adventures in Wonderland / Through the Looking Glass", "la Alice's Adventures in Wonderland / Through the Looking Glass", "Alice's Adventures in Wonderland / Through  Looking Glass", "un Alice's Adventures in Wonderland / Through the Looking Glass", "La Alice's Adventures in Wonderland / Through the Looking Glass", "ALICE'S ADVENTURES IN WONDERLAND / THROUGH THE LOOKING GLASS", "Une Alice's Adventures in Wonderland / Through the Looking Glass", "Alice's Adv in Wonderland / Through the Looking Glass", "An Alice's Adventures in Wonderland / Through the Looking Glass", "le Alice's Adventures in Wonderland / Through the Looking Glass", "The Alice's Adventures in Wonderland / Through the Looking Glass", "the Alice's Adventures in Wonderland / Through the Looking Glass", "Alice's Adventures in Wonderland / Through the Looking Glass"],
    first_published: 1889,
    status: "ongoing",
    languages: ["por", "und", "rus", "pol", "ger", "ita", "eng", "chi", "fre", "spa", "rum"],
    translations: {"en": "Alice's Adventures in Wonderland / Through the Looking Glass", "fr": "Alice's Adventures in Wonderland / Through the Looking Glass"},
    source: "open_library_search",
  },
  {
    name: "Around the World in",
    authors: ["Jules Verne"],
    category: "roman",
    volumes: 80,
    keywords: ["around the world in", "around the world in series", "around the world in saga", "the around the world in", "jules"],
    variations: ["Around the World in", "The Around the World in", "Around the World in Series"],
    subjects: ["Fiction, action & adventure", "Voyages and travels, fiction", "Continental european fiction (fictional works by one author)", "Adventure and adventurers, fiction", "Children's fiction"],
    source: "open_library_mega_expansion",
  },
  {
    name: "Death Note",
    authors: ["Tsugumi Ohba"],
    category: "roman",
    volumes: 12,
    keywords: ["death note", "death note series", "death note saga", "death note novel", "death note book", "ohba"],
    variations: ["Death Note", "The Death Note", "Death Note Series"],
    source: "open_library_mega_harvest",
  },
  {
    name: "Dorian Hunter",
    authors: ["Neal Davenport"],
    category: "roman",
    volumes: 17,
    keywords: ["dorian hunter", "dorian hunter series", "dorian hunter saga", "the dorian hunter", "neal"],
    variations: ["Dorian Hunter", "The Dorian Hunter", "Dorian Hunter Series"],
    source: "open_library_mega_expansion",
  },
  {
    name: "Dragon Ball,",
    authors: ["Akira Toriyama"],
    category: "roman",
    volumes: 12,
    keywords: ["dragon ball,", "dragon ball, series", "dragon ball, saga", "the dragon ball,", "akira"],
    variations: ["Dragon Ball,", "The Dragon Ball,", "Dragon Ball, Series"],
    source: "open_library_mega_expansion",
  },
  {
    name: "Final Truth, Truth Thriller",
    authors: ["Mariah Stewart"],
    category: "roman",
    volumes: 2,
    keywords: ["final truth, truth thriller", "final truth, truth thriller series", "final truth, truth thriller saga", "the final truth, truth thriller", "mariah"],
    variations: ["Final Truth, Truth Thriller", "The Final Truth, Truth Thriller", "Final Truth, Truth Thriller Series"],
    source: "open_library_mega_expansion",
  },
  {
    name: "Freaked Out Horror (series",
    authors: ["Tom Raimbault"],
    category: "roman",
    volumes: 5,
    keywords: ["freaked out horror (series", "freaked out horror (series series", "freaked out horror (series saga", "the freaked out horror (series", "tom"],
    variations: ["Freaked Out Horror (series", "The Freaked Out Horror (series", "Freaked Out Horror (series Series"],
    source: "open_library_mega_expansion",
  },
  {
    name: "Harry Potter",
    authors: ["J.K. Rowling"],
    category: "roman",
    volumes: 7,
    keywords: ["harry", "potter", "wizard", "hogwarts", "magic"],
    variations: ["Harry Potter", "HP", "Potter"],
    first_published: 1997,
    status: "completed",
    description: "Série de romans fantastiques",
    subjects: ["fantasy", "wizards", "magic", "children"],
    languages: ["en", "fr"],
    translations: {"en": "Harry Potter", "fr": "Harry Potter"},
    source: "manual",
  },
  {
    name: "House Atreides",
    authors: ["Brian Herbert"],
    category: "roman",
    volumes: 4,
    keywords: ["house atreides", "house atreides series", "house atreides saga", "house atreides novel", "house atreides book", "herbert"],
    variations: ["House Atreides", "The House Atreides", "House Atreides Series"],
    source: "open_library_mega_harvest",
  },
  {
    name: "Muchachas",
    authors: ["Katherine Pancol"],
    category: "roman",
    volumes: 3,
    keywords: ["muchachas", "muchachas series", "muchachas saga", "the muchachas", "katherine"],
    variations: ["Muchachas", "The Muchachas", "Muchachas Series"],
    source: "open_library_mega_expansion",
  },
  {
    name: "Mushoku Tensei (Light Novel) Vol.",
    authors: ["理不尽な孫の手"],
    category: "roman",
    volumes: 19,
    keywords: ["mushoku tensei (light novel) vol.", "mushoku tensei (light novel) vol. series", "mushoku tensei (light novel) vol. saga", "the mushoku tensei (light novel) vol.", "理不尽な孫の手"],
    variations: ["Mushoku Tensei (Light Novel) Vol.", "The Mushoku Tensei (Light Novel) Vol.", "Mushoku Tensei (Light Novel) Vol. Series"],
    source: "open_library_mega_expansion",
  },
  {
    name: "Oeuvres complètes,",
    authors: ["Frédéric Dard"],
    category: "roman",
    volumes: 24,
    keywords: ["oeuvres complètes,", "oeuvres complètes, series", "oeuvres complètes, saga", "dard"],
    variations: ["Oeuvres complètes,", "The Oeuvres complètes,", "Oeuvres complètes, Series"],
    source: "open_library_ultra_expansion",
  },
  {
    name: "Phönixakademie - Sammelband",
    authors: ["I. Bow"],
    category: "roman",
    volumes: 4,
    keywords: ["phönixakademie - sammelband", "phönixakademie - sammelband series", "phönixakademie - sammelband saga", "the phönixakademie - sammelband", "i."],
    variations: ["Phönixakademie - Sammelband", "The Phönixakademie - Sammelband", "Phönixakademie - Sammelband Series"],
    source: "open_library_mega_expansion",
  },
  {
    name: "San Antonio",
    authors: ["Frédéric Dard"],
    category: "roman",
    volumes: 3,
    keywords: ["san antonio", "san antonio series", "san antonio saga", "dard"],
    variations: ["San Antonio", "The San Antonio", "San Antonio Series"],
    source: "open_library_ultra_expansion",
  },
  {
    name: "Spirit",
    authors: ["Quality Comics"],
    category: "roman",
    volumes: 5,
    keywords: ["spirit", "spirit series", "spirit saga", "the spirit", "quality"],
    variations: ["Spirit", "The Spirit", "Spirit Series"],
    source: "open_library_mega_expansion",
  },
  {
    name: "Spring Series",
    authors: ["Jennifer Cross"],
    category: "roman",
    volumes: 2,
    keywords: ["spring series", "spring series series", "spring series saga", "cross"],
    variations: ["Spring Series", "The Spring Series", "Spring Series Series"],
    source: "open_library_ultra_expansion",
  },
  {
    name: "Star Trek",
    authors: ["James Blish"],
    category: "roman",
    volumes: 8,
    keywords: ["star trek", "star trek series", "star trek saga", "the star trek", "james"],
    variations: ["Star Trek", "The Star Trek", "Star Trek Series"],
    subjects: ["Fiction, science fiction, general", "Fiction", "American Science fiction", "English Short stories", "Nouvelles anglaises", "Star Trek fiction", "collectionID:STnov", "Children's stories", "Science fiction", "Star trek (Television program)"],
    source: "open_library_mega_expansion",
  },
  {
    name: "Star Wars - Thrawn",
    authors: ["Timothy Zahn"],
    category: "roman",
    volumes: 2,
    keywords: ["star wars - thrawn", "star wars - thrawn series", "star wars - thrawn saga", "the star wars - thrawn", "timothy"],
    variations: ["Star Wars - Thrawn", "The Star Wars - Thrawn", "Star Wars - Thrawn Series"],
    subjects: ["Fiction", "Princess Leia (Fictitious character)", "Star Wars fiction", "the thrawn trilogy", "Han Solo (Fictitious character)", "timothy zahn", "star wars", "Science fiction", "Luke Skywalker (Fictitious character)"],
    source: "open_library_mega_expansion",
  },
  {
    name: "Steeplejack:",
    authors: ["A. J. Hartley"],
    category: "roman",
    volumes: 1,
    keywords: ["steeplejack:", "steeplejack: series", "steeplejack: saga", "the steeplejack:", "a."],
    variations: ["Steeplejack:", "The Steeplejack:", "Steeplejack: Series"],
    subjects: ["Fantasy fiction", "South africa, fiction", "Mystery and detective stories", "Adventure and adventurers, fiction", "Children's fiction"],
    source: "open_library_mega_expansion",
  },
  {
    name: "Terry Goodkind Sword of Truth Series",
    authors: ["Terry Goodkind"],
    category: "roman",
    volumes: 2,
    keywords: ["terry goodkind sword of truth series", "terry goodkind sword of truth series series", "terry goodkind sword of truth series saga", "terry goodkind sword of truth series novel", "terry goodkind sword of truth series book", "goodkind"],
    variations: ["Terry Goodkind Sword of Truth Series", "The Terry Goodkind Sword of Truth Series", "Terry Goodkind Sword of Truth Series Series"],
    source: "open_library_mega_harvest",
  },
  {
    name: "The Adventures of Sherlock Holmes [12 stories]",
    authors: ["Arthur Conan Doyle"],
    category: "roman",
    volumes: 1,
    keywords: ["sherlock", "stories", "holmes", "adventures"],
    variations: ["the The Adventures of Sherlock Holmes [12 stories]", "The The Adventures of Sherlock Holmes [12 stories]", "The Adv of Sherlock Holmes [12 stories]", "THE ADVENTURES OF SHERLOCK HOLMES [12 STORIES]", "le The Adventures of Sherlock Holmes [12 stories]", "la The Adventures of Sherlock Holmes [12 stories]", "La The Adventures of Sherlock Holmes [12 stories]", "les The Adventures of Sherlock Holmes [12 stories]", "des The Adventures of Sherlock Holmes [12 stories]", "A The Adventures of Sherlock Holmes [12 stories]", "The Adventures Of Sherlock Holmes [12 Stories]", "Le The Adventures of Sherlock Holmes [12 stories]", "a The Adventures of Sherlock Holmes [12 stories]", "Une The Adventures of Sherlock Holmes [12 stories]", "Adventures of Sherlock Holmes [12 stories]", "an The Adventures of Sherlock Holmes [12 stories]", "the adventures of sherlock holmes [12 stories]", "The Adventures of Sherlock Holmes [12 stories]", "The Adventures  Sherlock Holmes [12 stories]", "une The Adventures of Sherlock Holmes [12 stories]", "Des The Adventures of Sherlock Holmes [12 stories]", "un The Adventures of Sherlock Holmes [12 stories]", "An The Adventures of Sherlock Holmes [12 stories]", "Les The Adventures of Sherlock Holmes [12 stories]", "Un The Adventures of Sherlock Holmes [12 stories]"],
    first_published: 1892,
    status: "ongoing",
    languages: ["gle", "eng", "cat", "tur", "dut", "srp", "por", "mon", "fre", "spa", "jpn", "pol", "chi", "gre", "ger", "may", "rus"],
    translations: {"en": "The Adventures of Sherlock Holmes [12 stories]", "fr": "The Adventures of Sherlock Holmes [12 stories]"},
    source: "open_library_search",
  },
  {
    name: "The Adventures of Tom Sawyer",
    authors: ["Mark Twain"],
    category: "roman",
    volumes: 1,
    keywords: ["sawyer", "tom", "adventures"],
    variations: ["The Adventures Of Tom Sawyer", "les The Adventures of Tom Sawyer", "une The Adventures of Tom Sawyer", "La The Adventures of Tom Sawyer", "Des The Adventures of Tom Sawyer", "An The Adventures of Tom Sawyer", "des The Adventures of Tom Sawyer", "the The Adventures of Tom Sawyer", "le The Adventures of Tom Sawyer", "A The Adventures of Tom Sawyer", "Les The Adventures of Tom Sawyer", "The Adventures of Tom Sawyer", "Le The Adventures of Tom Sawyer", "la The Adventures of Tom Sawyer", "The Adventures  Tom Sawyer", "an The Adventures of Tom Sawyer", "Une The Adventures of Tom Sawyer", "Un The Adventures of Tom Sawyer", "The The Adventures of Tom Sawyer", "a The Adventures of Tom Sawyer", "un The Adventures of Tom Sawyer", "The Adv of Tom Sawyer", "the adventures of tom sawyer", "Adventures of Tom Sawyer", "THE ADVENTURES OF TOM SAWYER"],
    first_published: 1817,
    status: "ongoing",
    languages: ["heb", "afr", "vie", "ita", "spa", "ben", "dut", "yid", "und", "rus", "fre", "eng", "urd", "por", "mul", "jpn", "pol", "mal", "ger", "cze", "chi", "per", "fin"],
    translations: {"en": "The Adventures of Tom Sawyer", "fr": "The Adventures of Tom Sawyer"},
    source: "open_library_search",
  },
  {
    name: "The Book of Lost",
    authors: ["J.R.R. Tolkien"],
    category: "roman",
    volumes: 2,
    keywords: ["the book of lost", "the book of lost series", "the book of lost saga", "the book of lost novel", "the book of lost book", "tolkien"],
    variations: ["The Book of Lost", "The The Book of Lost", "The Book of Lost Series"],
    source: "open_library_mega_harvest",
  },
  {
    name: "The Complete Life and Adventures of Santa Claus",
    authors: ["L. Frank Baum"],
    category: "roman",
    volumes: 1,
    keywords: ["life", "complete", "adventures"],
    variations: ["the The Complete Life and Adventures of Santa Claus", "la The Complete Life and Adventures of Santa Claus", "le The Complete Life and Adventures of Santa Claus", "Des The Complete Life and Adventures of Santa Claus", "a The Complete Life and Adventures of Santa Claus", "the complete life and adventures of santa claus", "THE COMPLETE LIFE AND ADVENTURES OF SANTA CLAUS", "Complete Life and Adventures of Santa Claus", "Les The Complete Life and Adventures of Santa Claus", "une The Complete Life and Adventures of Santa Claus", "les The Complete Life and Adventures of Santa Claus", "La The Complete Life and Adventures of Santa Claus", "The The Complete Life and Adventures of Santa Claus", "The Complete Life and Adventures  Santa Claus", "A The Complete Life and Adventures of Santa Claus", "An The Complete Life and Adventures of Santa Claus", "des The Complete Life and Adventures of Santa Claus", "The Complete Life & Adventures of Santa Claus", "The Complete Life and Adv of Santa Claus", "Un The Complete Life and Adventures of Santa Claus", "The Complete Life And Adventures Of Santa Claus", "an The Complete Life and Adventures of Santa Claus", "Le The Complete Life and Adventures of Santa Claus", "The Complete Life and Adventures of Santa Claus", "Une The Complete Life and Adventures of Santa Claus", "un The Complete Life and Adventures of Santa Claus"],
    first_published: 1902,
    status: "ongoing",
    languages: ["fre", "eng"],
    translations: {"en": "The Complete Life and Adventures of Santa Claus", "fr": "The Complete Life and Adventures of Santa Claus"},
    source: "open_library_search",
  },
  {
    name: "The Name of the Wind",
    authors: ["Patrick Rothfuss"],
    category: "roman",
    volumes: 2,
    keywords: ["the name of the wind", "the name of the wind series", "the name of the wind saga", "the name of the wind novel", "the name of the wind book", "rothfuss"],
    variations: ["The Name of the Wind", "The The Name of the Wind", "The Name of the Wind Series"],
    source: "open_library_mega_harvest",
  },
  {
    name: "Untitled Jack Ryan",
    authors: ["Marc Cameron"],
    category: "roman",
    volumes: 22,
    keywords: ["untitled jack ryan", "untitled jack ryan series", "untitled jack ryan saga", "the untitled jack ryan", "marc"],
    variations: ["Untitled Jack Ryan", "The Untitled Jack Ryan", "Untitled Jack Ryan Series"],
    source: "open_library_mega_expansion",
  },
  {
    name: "Vigor Mortis",
    authors: ["Natalie Maher"],
    category: "roman",
    volumes: 3,
    keywords: ["vigor mortis", "vigor mortis series", "vigor mortis saga", "the vigor mortis", "natalie"],
    variations: ["Vigor Mortis", "The Vigor Mortis", "Vigor Mortis Series"],
    subjects: ["Body Horror", "Magic", "Fantasy", "Multiple Perspectives"],
    source: "open_library_mega_expansion",
  },
  {
    name: "Web of Mystery",
    authors: ["Kari Therrian"],
    category: "roman",
    volumes: 12,
    keywords: ["web of mystery", "web of mystery series", "web of mystery saga", "the web of mystery", "kari"],
    variations: ["Web of Mystery", "The Web of Mystery", "Web of Mystery Series"],
    source: "open_library_mega_expansion",
  },
  {
    name: "Web of Mystery Collection",
    authors: ["Ace Books"],
    category: "roman",
    volumes: 1,
    keywords: ["web of mystery collection", "web of mystery collection series", "web of mystery collection saga", "the web of mystery collection", "ace"],
    variations: ["Web of Mystery Collection", "The Web of Mystery Collection", "Web of Mystery Collection Series"],
    source: "open_library_mega_expansion",
  },
  {
    name: "Astérix",
    authors: ["René Goscinny", "Albert Uderzo"],
    category: "bd",
    volumes: 39,
    keywords: ["asterix", "obelix", "gaulois", "roman", "comic"],
    variations: ["Astérix", "Asterix", "Astérix le Gaulois"],
    first_published: 1959,
    status: "ongoing",
    description: "Série de bande dessinée française",
    subjects: ["comic", "french", "historical", "humor"],
    languages: ["fr", "en"],
    translations: {"en": "Asterix", "fr": "Astérix"},
    source: "manual",
  },
  {
    name: "Attack On Titan",
    authors: ["諫山創"],
    category: "bd",
    volumes: 13,
    keywords: ["attack on titan", "attack on titan series", "attack on titan saga", "attack on titan comic", "attack on titan bd", "諫山創"],
    variations: ["Attack On Titan", "The Attack On Titan", "Attack On Titan Series"],
    source: "open_library_mega_harvest",
  },
  {
    name: "Fullmetal Alchemist",
    authors: ["荒川 弘"],
    category: "bd",
    volumes: 22,
    keywords: ["fullmetal alchemist", "fullmetal alchemist series", "fullmetal alchemist saga", "fullmetal alchemist comic", "fullmetal alchemist bd"],
    variations: ["Fullmetal Alchemist", "The Fullmetal Alchemist", "Fullmetal Alchemist Series"],
    source: "open_library_mega_harvest",
  },
  {
    name: "Le Petit Spirou",
    authors: ["Tome"],
    category: "bd",
    volumes: 2,
    keywords: ["le petit spirou", "le petit spirou series", "le petit spirou saga", "le petit spirou comic", "le petit spirou bd", "tome"],
    variations: ["Le Petit Spirou", "The Le Petit Spirou", "Le Petit Spirou Series"],
    source: "open_library_mega_harvest",
  },
  {
    name: "Lucky Luke",
    authors: ["Morris"],
    category: "bd",
    volumes: 68,
    keywords: ["lucky luke", "lucky luke series", "lucky luke saga", "lucky luke comic", "lucky luke bd", "morris"],
    variations: ["Lucky Luke", "The Lucky Luke", "Lucky Luke Series"],
    source: "open_library_mega_harvest",
  },
  {
    name: "New Excalibur",
    authors: ["Michael Ryan (comic book artist)"],
    category: "bd",
    volumes: 2,
    keywords: ["new excalibur", "new excalibur series", "new excalibur saga", "artist)"],
    variations: ["New Excalibur", "The New Excalibur", "New Excalibur Series"],
    source: "open_library_ultra_expansion",
  },
  {
    name: "Saga,",
    authors: ["Brian K. Vaughan"],
    category: "bd",
    volumes: 6,
    keywords: ["saga,", "saga, series", "saga, saga", "vaughan"],
    variations: ["Saga,", "The Saga,", "Saga, Series"],
    source: "open_library_ultra_expansion",
  },
  {
    name: "Spirou et Fantasio",
    authors: ["André Franquin"],
    category: "bd",
    volumes: 17,
    keywords: ["spirou et fantasio", "spirou et fantasio series", "spirou et fantasio saga", "spirou et fantasio comic", "spirou et fantasio bd", "franquin"],
    variations: ["Spirou et Fantasio", "The Spirou et Fantasio", "Spirou et Fantasio Series"],
    source: "open_library_mega_harvest",
  },
  {
    name: "Buddha,",
    authors: ["Osamu Tezuka"],
    category: "manga",
    volumes: 7,
    keywords: ["buddha,", "buddha, series", "buddha, saga", "the buddha,", "osamu"],
    variations: ["Buddha,", "The Buddha,", "Buddha, Series"],
    subjects: ["Comics & graphic novels, manga, general", "Comics & graphic novels, manga, fantasy"],
    source: "open_library_mega_expansion",
  },
  {
    name: "Death Note, Vol.",
    authors: ["Tsugumi Ohba"],
    category: "manga",
    volumes: 12,
    keywords: ["death note, vol.", "death note, vol. series", "death note, vol. saga", "the death note, vol.", "tsugumi"],
    variations: ["Death Note, Vol.", "The Death Note, Vol.", "Death Note, Vol. Series"],
    subjects: ["series:death_note", "Death", "Fiction", "Comic books, strips", "high school students", "gods", "Students", "United States", "Good and evil", "Criminals"],
    source: "open_library_mega_expansion",
  },
  {
    name: "Demon Slayer : Kimetsu No Yaiba",
    authors: ["Koyoharu Gotōge"],
    category: "manga",
    volumes: 13,
    keywords: ["demon slayer : kimetsu no yaiba", "demon slayer : kimetsu no yaiba series", "demon slayer : kimetsu no yaiba saga", "demon slayer : kimetsu no yaiba manga", "demon slayer : kimetsu no yaiba light novel", "gotōge"],
    variations: ["Demon Slayer : Kimetsu No Yaiba", "The Demon Slayer : Kimetsu No Yaiba", "Demon Slayer : Kimetsu No Yaiba Series"],
    source: "open_library_mega_harvest",
  },
  {
    name: "Dragon Ball Z",
    authors: ["Akira Toriyama"],
    category: "manga",
    volumes: 19,
    keywords: ["dragon ball z", "dragon ball z series", "dragon ball z saga", "dragon ball z manga", "dragon ball z light novel", "toriyama"],
    variations: ["Dragon Ball Z", "The Dragon Ball Z", "Dragon Ball Z Series"],
    source: "open_library_mega_harvest",
  },
  {
    name: "Dragon Ball Z,",
    authors: ["Akira Toriyama"],
    category: "manga",
    volumes: 21,
    keywords: ["dragon ball z,", "dragon ball z, series", "dragon ball z, saga", "the dragon ball z,", "akira"],
    variations: ["Dragon Ball Z,", "The Dragon Ball Z,", "Dragon Ball Z, Series"],
    subjects: ["Graphic novels", "Fiction", "Comic books, strips", "Martial arts fiction", "Martial artists", "Comics & graphic novels, general", "Children's fiction", "Translations into English", "Juvenile fiction", "Quests (Expeditions)"],
    source: "open_library_mega_expansion",
  },
  {
    name: "Dragon Ball Z, Vol.",
    authors: ["Akira Toriyama"],
    category: "manga",
    volumes: 7,
    keywords: ["dragon ball z, vol.", "dragon ball z, vol. series", "dragon ball z, vol. saga", "the dragon ball z, vol.", "akira"],
    variations: ["Dragon Ball Z, Vol.", "The Dragon Ball Z, Vol.", "Dragon Ball Z, Vol. Series"],
    subjects: ["Graphic novels", "Fiction", "Fantasy comic books, strips", "Martial artists", "Comics & graphic novels, general", "Comics & graphic novels, manga, fantasy", "Extraterrestrial beings", "Juvenile fiction", "Quests (Expeditions)"],
    source: "open_library_mega_expansion",
  },
  {
    name: "Dragon Ball, Vol.",
    authors: ["Akira Toriyama"],
    category: "manga",
    volumes: 11,
    keywords: ["dragon ball, vol.", "dragon ball, vol. series", "dragon ball, vol. saga", "the dragon ball, vol.", "akira"],
    variations: ["Dragon Ball, Vol.", "The Dragon Ball, Vol.", "Dragon Ball, Vol. Series"],
    subjects: ["Fiction", "Martial artists", "Children's fiction", "Comics & graphic novels, manga, fantasy", "Dragón ball vol5", "Juvenile fiction", "Quests (Expeditions)"],
    source: "open_library_mega_expansion",
  },
  {
    name: "InuYasha,",
    authors: ["高橋留美子"],
    category: "manga",
    volumes: 10,
    keywords: ["inuyasha,", "inuyasha, series", "inuyasha, saga", "高橋留美子"],
    variations: ["InuYasha,", "The InuYasha,", "InuYasha, Series", "InuYasha, Light Novel", "InuYasha, LN"],
    source: "open_library_ultra_expansion",
  },
  {
    name: "Les Tuniques Bleues,",
    authors: ["Raoul Cauvin"],
    category: "manga",
    volumes: 42,
    keywords: ["les tuniques bleues,", "les tuniques bleues, series", "les tuniques bleues, saga", "the les tuniques bleues,", "raoul"],
    variations: ["Les Tuniques Bleues,", "The Les Tuniques Bleues,", "Les Tuniques Bleues, Series"],
    subjects: ["Funny military comic books, strips", "Franco-Belgian comic books, strips", "series:les_tuniques_bleues", "Western comic books, strips"],
    source: "open_library_mega_expansion",
  },
  {
    name: "Liz and Beth Vol.",
    authors: ["G. Levis"],
    category: "manga",
    volumes: 3,
    keywords: ["liz and beth vol.", "liz and beth vol. series", "liz and beth vol. saga", "the liz and beth vol.", "g."],
    variations: ["Liz and Beth Vol.", "The Liz and Beth Vol.", "Liz and Beth Vol. Series"],
    subjects: ["Comic books, strips", "Franco-Belgian comic books, strips", "Erotic comic books, strips", "Lesbians", "Translations into English"],
    source: "open_library_mega_expansion",
  },
  {
    name: "My Hero Academia",
    authors: ["Kohei Horikoshi"],
    category: "manga",
    volumes: 32,
    keywords: ["my hero academia", "my hero academia series", "my hero academia saga", "my hero academia manga", "my hero academia light novel", "horikoshi"],
    variations: ["My Hero Academia", "The My Hero Academia", "My Hero Academia Series"],
    source: "open_library_mega_harvest",
  },
  {
    name: "Naruto",
    authors: ["Masashi Kishimoto"],
    category: "manga",
    volumes: 25,
    keywords: ["naruto", "naruto series", "naruto saga", "naruto manga", "naruto light novel", "kishimoto"],
    variations: ["Naruto", "The Naruto", "Naruto Series"],
    source: "open_library_mega_harvest",
  },
  {
    name: "Naruto, Vol.",
    authors: ["Masashi Kishimoto"],
    category: "manga",
    volumes: 2,
    keywords: ["naruto, vol.", "naruto, vol. series", "naruto, vol. saga", "the naruto, vol.", "masashi"],
    variations: ["Naruto, Vol.", "The Naruto, Vol.", "Naruto, Vol. Series"],
    subjects: ["Graphic novels", "Fiction", "Comic books, strips", "Ninja", "Pariahs"],
    source: "open_library_mega_expansion",
  },
  {
    name: "One Piece",
    authors: ["Eiichiro Oda"],
    category: "manga",
    volumes: 105,
    keywords: ["one", "piece", "luffy", "pirates", "treasure"],
    variations: ["One Piece", "OP", "Wan Pīsu"],
    first_published: 1997,
    status: "ongoing",
    description: "Manga d'aventure et de pirates",
    subjects: ["manga", "pirates", "adventure", "shonen"],
    languages: ["ja", "fr", "en"],
    translations: {"en": "One Piece", "fr": "One Piece", "ja": "ワンピース"},
    source: "manual",
  },
  {
    name: "Pokemon",
    authors: ["Hidenori Kusaka"],
    category: "manga",
    volumes: 2,
    keywords: ["pokemon", "pokemon series", "pokemon saga", "the pokemon", "hidenori"],
    variations: ["Pokemon", "The Pokemon", "Pokemon Series"],
    subjects: ["Comic books, strips", "Pokémon (Fictitious characters)", "Mythical Animals", "Juvenile fiction", "Pokémon (Game)"],
    source: "open_library_mega_expansion",
  },
  {
    name: "Pokemon Adventures,",
    authors: ["Hidenori Kusaka"],
    category: "manga",
    volumes: 3,
    keywords: ["pokemon adventures,", "pokemon adventures, series", "pokemon adventures, saga", "the pokemon adventures,", "hidenori"],
    variations: ["Pokemon Adventures,", "The Pokemon Adventures,", "Pokemon Adventures, Series"],
    subjects: ["Pokemon (Game)", "Fiction", "Comic books, strips", "Pokémon (Fictitious characters)", "Cartoons and comics", "Pokémon (Game)", "Pokemon (Fictitious characters)"],
    source: "open_library_mega_expansion",
  },
  {
    name: "Wicked Lovely Desert",
    authors: ["Melissa Marr"],
    category: "manga",
    volumes: 4,
    keywords: ["wicked lovely desert", "wicked lovely desert series", "wicked lovely desert saga", "the wicked lovely desert", "melissa"],
    variations: ["Wicked Lovely Desert", "The Wicked Lovely Desert", "Wicked Lovely Desert Series"],
    subjects: ["Graphic novels", "Fairies", "Comic books, strips"],
    source: "open_library_mega_expansion",
  }
];

// Statistiques base de données
export const SERIES_STATS = {
  total_series: 58,
  by_category: {
    roman: 33,
    bd: 8,
    manga: 17
  },
  total_volumes: 757,
  avg_volumes_per_series: 13.1,
  last_updated: "2025-07-12 01:37:56"
};

// Fonctions utilitaires
export const getSeriesByCategory = (category) => {
  return EXTENDED_SERIES_DATABASE.filter(series => series.category === category);
};

export const getSeriesByAuthor = (author) => {
  return EXTENDED_SERIES_DATABASE.filter(series => 
    series.authors.some(a => a.toLowerCase().includes(author.toLowerCase()))
  );
};

export const searchSeries = (query) => {
  const queryLower = query.toLowerCase();
  return EXTENDED_SERIES_DATABASE.filter(series => 
    series.name.toLowerCase().includes(queryLower) ||
    series.authors.some(a => a.toLowerCase().includes(queryLower)) ||
    series.keywords.some(k => k.toLowerCase().includes(queryLower))
  );
};

// Export par défaut
export default EXTENDED_SERIES_DATABASE;
