[pytest]
pythonpath = .
asyncio_mode = auto
asyncio_default_fixture_loop_scope = function
markers =
    asyncio: tests asyncio (compat)
filterwarnings =
    ignore:Unknown pytest.mark.asyncio:pytest.PytestUnknownMarkWarning
